WEB_053502_YUREV/WEB_053502_YUREV/Components/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WEB_053502_YUREV.Models;

namespace WEB_053502_YUREV.Components;

public class CartViewComponent : ViewComponent
{
    private Cart _cart;
    
    public CartViewComponent(Cart cart)
    {
        _cart = cart;
    }
    
    public async Task<IViewComponentResult> InvokeAsync()
    {
        return View(_cart);
    }
}

WEB_053502_YUREV/WEB_053502_YUREV/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WEB_053502_YUREV.Models;

namespace WEB_053502_YUREV.Components;

public class MenuViewComponent : ViewComponent
{
    private List<MenuItem> _menuItems = new List<MenuItem>
    {
        new MenuItem { 
            Controller="Home", 
            Action="Index", 
            Text="Lab 2"
        },
        new MenuItem { 
            Controller="Product", 
            Action="Index",
            Text="Каталог"
        },
        new MenuItem { 
            IsPage=true, 
            Area="Admin", 
            Page="/Index",
            Text="Администрирование"
        }
    };

    public IViewComponentResult Invoke()
    {
        var currentController = ViewContext.RouteData.Values["controller"];
        var currentPage = ViewContext.RouteData.Values["page"];
        var currentArea = ViewContext.RouteData.Values["area"];

        foreach (var item in _menuItems)
        {
            bool areaCheck = currentArea != null && currentArea.Equals(item.Area);
            bool controllerCheck = currentArea != null && currentArea.Equals(item.Controller);
            if (areaCheck || controllerCheck)
            {
                item.Active = "active";
            }
        }
        return View(_menuItems);
    }
}

WEB_053502_YUREV/WEB_053502_YUREV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WEB_053502_YUREV</title>
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WEB_053502_YUREV.styles.css" asp-append-version="true"/>
</head>
    <body>
        <header>
            <div class="container">
                <nav class="navbar navbar-expand-md navbar-dark bg-grey">
                    <a class="navbar-brand" href="#">WebLabsV06</a>
                    <div class="navbar-nav">
                        @await Component.InvokeAsync("Menu")
                    </div>
                    <partial name="_UserPartial" />
                </nav> <!-- Панель навигации - конец -->
            </div><!-- container - конец -->
        </header><!-- header - конец -->
    <main class="container-fluid" style="min-height: 84vh">
        @RenderBody()
    </main>
        <footer>
            <div class="container">
                <div class="navbar navbar-dark navbar-expand-md bg-grey">
                    <div class="navbar-nav ms-auto">
                        <a class="nav-item nav-link" href="http://www.facebook.com">
                            <i class="fab fa-facebook-f fa-2x"></i>
                        </a>
                        <a class="nav-item nav-link" href="http://www.vk.com">
                            <i class="fab fa-vk fa-2x"></i>
                        </a>
                        <a class="nav-item nav-link" href="http://www.twitter.com">
                            <i class="fab fa-twitter fa-2x"></i>
                        </a> </div>
                </div>
            </div>
        </footer>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

WEB_053502_YUREV/WEB_053502_YUREV/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> signInManager

@if (signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ms-4 nav-color">
        <div class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="true">
            <img img-controller="Home"
                   img-action="GetAvatar"
                   onerror="this.onerror=null; this.src='@Url.Content("~/images/avatar.png")'"
                   width="40" height="40" alt="@User.Identity.Name" class="rounded"/>
        </div>
        <ul class="dropdown-menu"
            aria-labelledby="dropdownMenuButton">
            <li>
                <div class="dropdown-item-text">
                    <img img-controller="Home"
                           img-action="GetAvatar"
                           onerror="this.onerror=null; this.src='@Url.Content("~/images/avatar.png")'"
                           width="40" height="40" alt="@User.Identity.Name" class="rounded"/>
                    @User.Identity.Name
                </div>
            </li>
            <li>
            <div class="dropdown-divider"></div>
            <li>
                <a class="dropdown-item" asp-controller="Cart" asp-action="Index">Корзина</a>
            </li>
            <li>
                <a class="dropdown-item" asp-controller="Product" asp-action="">Мои товары</a>
            </li>
            <li>
                <form id="form-inline" class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <a href="javascript:{}" onclick="document.getElementById('form-inline').submit()">Log out</a>
                </form>
            </li>
        </ul>
    </div>
}
else
{
    <div class="nav navbar-nav navbar-right">
        <a class="nav-item nav-link" asp-area="Identity" asp-page="/Account/Login">Вход</a>
        <a class="nav-item nav-link" asp-area="Identity" asp-page="/Account/Register">Регистрация</a>
    </div>
}
<!-- Информация пользователя - конец -->